Q1. Write a program to create a NumPy 1D-array with 5 elements and perform basic operations like:
a) Addition of 2 in all the element
b) Multiply 3 with all the elements
c) Divide every element by 2

In [1]:
import numpy as np

arr = np.array([12, 45, 7, 23, 34])
print(arr)

[12 45  7 23 34]


In [2]:
add_arr = arr + 2
print(add_arr)

[14 47  9 25 36]


In [3]:
mul_arr = arr * 3
print(mul_arr)

[ 36 135  21  69 102]


In [4]:
div_arr = arr / 2
print(div_arr)

[ 6.  22.5  3.5 11.5 17. ]


Q2. Questions on Basic NumPy Array:
a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])
b) Find the most frequent value and their indice(s) in the following arrays:
i. x = np.array([1,2,3,4,5,1,2,1,1,1])
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

In [5]:
arr2 = np.array([1, 2, 3, 6, 4, 5])
rev_arr = arr2[::-1]
print(rev_arr)

[5 4 6 3 2 1]


In [6]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
vals, counts = np.unique(x, return_counts=True)
freq_val = vals[np.argmax(counts)]
indices = np.where(x == freq_val)
print(freq_val)
print(indices)

1
(array([0, 5, 7, 8, 9]),)


In [7]:
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
vals2, counts2 = np.unique(y, return_counts=True)
freq_val2 = vals2[np.argmax(counts2)]
indices2 = np.where(y == freq_val2)
print(freq_val2)
print(indices2)

1
(array([0, 1, 2]),)


Q3. For the given 2-D array arr=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]]), access elements using row and column indices as follows:
a) Access 1st row, 2nd column
b) Access 3rd row, 1st column

In [8]:
arr3 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr3[0][1])

20


In [9]:
print(arr3[2][0])

70


Q4. Write program to create an 1-D NumPy array named kshitiz_poudel with evenly spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array, shape, total elements, the data type of each element and total number of bytes consumed by the array. Find the transpose of this array using reshape() attribute. Can we do the same with T attribute?

In [10]:
kshitiz_poudel = np.linspace(10, 100, 25)
print(kshitiz_poudel)

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [11]:
print(kshitiz_poudel.ndim)
print(kshitiz_poudel.shape)
print(kshitiz_poudel.size)
print(kshitiz_poudel.dtype)
print(kshitiz_poudel.nbytes)

1
(25,)
25
float64
200


In [12]:
transpose_reshape = kshitiz_poudel.reshape(25, 1)
print(transpose_reshape)

[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]


Since kshitiz_poudel is a 1-D array, using the T attribute does not change it, as transpose has no effect on 1-D arrays. reshape() is needed to actually turn it into a column array.

In [13]:
transpose_T = kshitiz_poudel.T
print(transpose_T)
print(transpose_T.shape)

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
(25,)


Q5. Create a 2-D Array of three rows and four columns, named ucs420_kshitiz with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean, median, max, min, unique elements. Reshape the array to four rows and three columns and name it as reshaped_ucs420_kshitiz. Resize the array to two rows and three columns and name it as resized_ucs420_kshitiz.

In [14]:
ucs420_kshitiz = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 15, 20, 35]])
print(ucs420_kshitiz)

[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]


In [15]:
mean_val = np.mean(ucs420_kshitiz)
median_val = np.median(ucs420_kshitiz)
max_val = np.max(ucs420_kshitiz)
min_val = np.min(ucs420_kshitiz)
unique_val = np.unique(ucs420_kshitiz)

print(mean_val)
print(median_val)
print(max_val)
print(min_val)
print(unique_val)

43.333333333333336
37.5
90
10
[10 15 20 30 35 40 50 60 70 80 90]


In [16]:
reshaped_ucs420_kshitiz = ucs420_kshitiz.reshape(4, 3)
print(reshaped_ucs420_kshitiz)

[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]


In [17]:
resized_ucs420_kshitiz = np.resize(ucs420_kshitiz, (2, 3))
print(resized_ucs420_kshitiz)

[[10 20 30]
 [40 50 60]]
